### ISSUE TITLE
xLODGen.85.7z is not avaliable for downloading anymore

### ISSUE THREAD

**Issue by atercygnus** [Althro/Tinvaak2#22]
**Describe the bug**
During installation process i encountered an issue:

```
17,16 - Found 1351 total files, 1338 matching filesize
17,4 - Unable to download xLODGen.85.7z (MegaDownloader+State|https://mega.nz/file/kNRCHRDY#ONIMDnlxyyBH-QsSUgatbQJWOgGGrr8F8bxWD_-bSGc)
17,4 - Cannot continue, was unable to download one or more archives
17,4 - File hash check (-42) d108d168dcefe4267b10aec5a86a75ebafbccb5015bf4a915e2adb8e8cd43793
17,41 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 70
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
17,81 - File hash check (-42) d108d168dcefe4267b10aec5a86a75ebafbccb5015bf4a915e2adb8e8cd43793
```

It trays to download xLODGen.85.7z from MegaDownloader, but the [link ](https://mega.nz/file/kNRCHRDY#ONIMDnlxyyBH-QsSUgatbQJWOgGGrr8F8bxWD_-bSGc)is dead, and I cannot find it anywhere else.

UPD: found xLODGen **85** [here](https://www.reddit.com/r/wabbajack/comments/s58pl3/xlodgen_85/), but anyway, need to repair an installer.

**To Reproduce**
Install Tinvaak2. Or just go just go to the link and make sure it doesn't work.

**Expected behavior**
Installation process should proceed smoothly, link should work.

**Modlist version**
2.1

**Did you add any additional mods?**
No

**Comment by chri3i** [comment]
Untill the list gets updated you need to download the one you found or the one found in the Discord server of the list. 
There is no way to 'repair' the link right now

**Comment by Althro** [comment]
Keeping this open so I can track this to ensure I update it for the next version.
